// Package docs Code generated by drp-go-cli. DO NOT EDIT.
// This file is a stub — run 'swag init' to regenerate.
package docs

import "github.com/swaggo/swag"

// SwaggerInfo holds the swagger specification.
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "drp API",
	Description:      "API generated by drp-go-cli",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
