// Package auth provides API-level documentation for Swaggo/swagger.
//
// @Title drp API
// @Description API generated by drp-go-cli
// @Version 1.0
// @Host localhost:8080
// @BasePath /
package auth
