package generator

import (
	"fmt"
	"path/filepath"
	"strings"
)

func authProjectFiles(opts ProjectOptions) map[string]string {
	mod := opts.ModuleName

	return map[string]string{
		"go.mod": fmt.Sprintf(`module %s

go %s

require (
	github.com/golang-jwt/jwt/v5 v5.3.1
	github.com/joho/godotenv v1.5.1
	github.com/lib/pq v1.10.9
	golang.org/x/crypto v0.24.0
)
`, mod, getGoVersion()),

		".env": strings.Join([]string{
			"# Database configuration",
			"DB_DRIVER=postgres",
			"DB_HOST=127.0.0.1",
			"DB_PORT=5432",
			"DB_USER=postgres",
			"DB_PASSWORD=secret",
			fmt.Sprintf("DB_NAME=%s", opts.Name),
			"DB_SSLMODE=disable",
			"",
			"# Application",
			"APP_PORT=8080",
			"",
			"# Auth",
			"JWT_SECRET=change-me-to-a-long-random-secret",
			"ACCESS_TOKEN_EXPIRY_MINUTES=15",
			"REFRESH_TOKEN_EXPIRY_DAYS=30",
			"ENCRYPTION_KEY=change-me-32-byte-random-key",
		}, "\n") + "\n",

		".env.example": strings.Join([]string{
			"DB_DRIVER=postgres",
			"DB_HOST=127.0.0.1",
			"DB_PORT=5432",
			"DB_USER=",
			"DB_PASSWORD=",
			fmt.Sprintf("DB_NAME=%s", opts.Name),
			"DB_SSLMODE=disable",
			"APP_PORT=8080",
			"JWT_SECRET=",
			"ACCESS_TOKEN_EXPIRY_MINUTES=15",
			"REFRESH_TOKEN_EXPIRY_DAYS=30",
			"ENCRYPTION_KEY=",
		}, "\n") + "\n",

		filepath.Join("cmd", "api", "main.go"): authMainGo(mod),
		filepath.Join("internal", "config", "config.go"): fmt.Sprintf(`package config

import (
	"fmt"
	"os"
	"strconv"
)

type Config struct {
	DBDriver string
	DBHost string
	DBPort string
	DBUser string
	DBPassword string
	DBName string
	DBSSLMode string
	AppPort string
	JWTSecret string
	AccessTokenExpiryMinutes int
	RefreshTokenExpiryDays int
	EncryptionKey string
}

func Load() *Config {
	return &Config{
		DBDriver: getenv("DB_DRIVER", "postgres"),
		DBHost: getenv("DB_HOST", "127.0.0.1"),
		DBPort: getenv("DB_PORT", "5432"),
		DBUser: getenv("DB_USER", "postgres"),
		DBPassword: getenv("DB_PASSWORD", ""),
		DBName: getenv("DB_NAME", "%s"),
		DBSSLMode: getenv("DB_SSLMODE", "disable"),
		AppPort: getenv("APP_PORT", "8080"),
		JWTSecret: getenv("JWT_SECRET", "change-me-to-a-long-random-secret"),
		AccessTokenExpiryMinutes: getenvInt("ACCESS_TOKEN_EXPIRY_MINUTES", 15),
		RefreshTokenExpiryDays: getenvInt("REFRESH_TOKEN_EXPIRY_DAYS", 30),
		EncryptionKey: getenv("ENCRYPTION_KEY", ""),
	}
}

func (c *Config) PostgresDSN() string {
	return fmt.Sprintf(
		"host=%%s port=%%s user=%%s password=%%s dbname=%%s sslmode=%%s",
		c.DBHost, c.DBPort, c.DBUser, c.DBPassword, c.DBName, c.DBSSLMode,
	)
}

func getenv(key, fallback string) string {
	if v := os.Getenv(key); v != "" {
		return v
	}
	return fallback
}

func getenvInt(key string, fallback int) int {
	v, err := strconv.Atoi(getenv(key, ""))
	if err != nil {
		return fallback
	}
	return v
}
`, opts.Name),

		filepath.Join("internal", "auth", "jwt.go"):                             authJWTGo(mod),
		filepath.Join("internal", "auth", "token_store.go"):                     authTokenStoreGo(),
		filepath.Join("internal", "middleware", "auth.go"):                      authMiddlewareGo(mod),
		filepath.Join("internal", "models", "user.go"):                          authUserModelGo(),
		filepath.Join("internal", "repositories", "user_repository.go"):         authUserRepositoryGo(mod),
		filepath.Join("internal", "services", "user_service.go"):                authUserServiceGo(mod),
		filepath.Join("internal", "handlers", "auth_handler.go"):                authHandlerGo(mod),
		filepath.Join("internal", "routes", "routes.go"):                        authRoutesGo(mod),
		filepath.Join("database", "migrations", "000001_create_users.up.sql"):   authUsersMigrationUp(),
		filepath.Join("database", "migrations", "000001_create_users.down.sql"): "DROP TABLE IF EXISTS user_tokens;\nDROP TABLE IF EXISTS users;\n",

		"README.md": fmt.Sprintf(`# %s

Generated by [DRP](https://github.com/DarpanAdhikari/drp-go-cli) with JWT auth.

## Getting started

`+"```bash"+`
cp .env.example .env
# edit .env, especially JWT_SECRET and ENCRYPTION_KEY
drp migrate:seed
go mod tidy
drp run api
`+"```"+`

Auth routes:

- POST /auth/register
- POST /auth/login
- POST /auth/refresh
- POST /auth/logout
- GET /me
`, opts.Name),
	}
}

func authMainGo(mod string) string {
	return fmt.Sprintf(`package main

import (
	"database/sql"
	"log"
	"net/http"

	_ "github.com/lib/pq"
	"github.com/joho/godotenv"

	"%s/internal/config"
	"%s/internal/routes"
)

func main() {
	if err := godotenv.Load(); err != nil {
		log.Printf("warning: .env not found: %%v", err)
	}

	cfg := config.Load()
	db, err := sql.Open("postgres", cfg.PostgresDSN())
	if err != nil {
		log.Fatal("db connect:", err)
	}
	defer db.Close()

	if err := db.Ping(); err != nil {
		log.Fatal("db ping:", err)
	}

	mux := http.NewServeMux()
	routes.Register(mux, db, cfg)

	log.Printf("listening on :%%s", cfg.AppPort)
	if err := http.ListenAndServe(":"+cfg.AppPort, mux); err != nil {
		log.Fatal(err)
	}
}
`, mod, mod)
}

func authJWTGo(mod string) string {
	return fmt.Sprintf(`package auth

import (
	"crypto/rand"
	"crypto/sha256"
	"encoding/base64"
	"encoding/hex"
	"fmt"
	"time"

	"github.com/golang-jwt/jwt/v5"

	"%s/internal/config"
	"%s/internal/models"
)

const (
	TokenTypeAccess = "access"
	TokenTypeRefresh = "refresh"
)

type Claims struct {
	UserID int64 `+"`json:\"user_id\"`"+`
	Email string `+"`json:\"email\"`"+`
	TokenType string `+"`json:\"token_type\"`"+`
	jwt.RegisteredClaims
}

type TokenPair struct {
	AccessToken string `+"`json:\"access_token\"`"+`
	RefreshToken string `+"`json:\"refresh_token\"`"+`
	TokenType string `+"`json:\"token_type\"`"+`
	AccessTokenExpiresAt time.Time `+"`json:\"access_token_expires_at\"`"+`
	RefreshTokenExpiresAt time.Time `+"`json:\"refresh_token_expires_at\"`"+`
}

func GenerateTokenPair(u *models.User, cfg *config.Config) (*TokenPair, *Claims, *Claims, error) {
	now := time.Now()
	accessExp := now.Add(time.Duration(cfg.AccessTokenExpiryMinutes) * time.Minute)
	refreshExp := now.AddDate(0, 0, cfg.RefreshTokenExpiryDays)

	accessToken, accessClaims, err := generateToken(u, cfg, TokenTypeAccess, accessExp, now)
	if err != nil {
		return nil, nil, nil, err
	}
	refreshToken, refreshClaims, err := generateToken(u, cfg, TokenTypeRefresh, refreshExp, now)
	if err != nil {
		return nil, nil, nil, err
	}

	return &TokenPair{
		AccessToken: accessToken,
		RefreshToken: refreshToken,
		TokenType: "Bearer",
		AccessTokenExpiresAt: accessExp,
		RefreshTokenExpiresAt: refreshExp,
	}, accessClaims, refreshClaims, nil
}

func generateToken(u *models.User, cfg *config.Config, tokenType string, exp, now time.Time) (string, *Claims, error) {
	jti, err := newJTI()
	if err != nil {
		return "", nil, err
	}

	claims := &Claims{
		UserID: u.ID,
		Email: u.Email,
		TokenType: tokenType,
		RegisteredClaims: jwt.RegisteredClaims{
			ExpiresAt: jwt.NewNumericDate(exp),
			IssuedAt: jwt.NewNumericDate(now),
			ID: jti,
			Subject: fmt.Sprintf("%%d", u.ID),
		},
	}

	token := jwt.NewWithClaims(jwt.SigningMethodHS256, claims)
	signed, err := token.SignedString([]byte(cfg.JWTSecret))
	if err != nil {
		return "", nil, err
	}
	return signed, claims, nil
}

func ParseToken(tokenStr string, cfg *config.Config) (*Claims, error) {
	token, err := jwt.ParseWithClaims(tokenStr, &Claims{}, func(t *jwt.Token) (interface{}, error) {
		if t.Method != jwt.SigningMethodHS256 {
			return nil, fmt.Errorf("unexpected signing method: %%s", t.Method.Alg())
		}
		return []byte(cfg.JWTSecret), nil
	})
	if err != nil {
		return nil, err
	}
	if claims, ok := token.Claims.(*Claims); ok && token.Valid {
		return claims, nil
	}
	return nil, jwt.ErrTokenInvalidClaims
}

func HashToken(tokenStr string) string {
	sum := sha256.Sum256([]byte(tokenStr))
	return hex.EncodeToString(sum[:])
}

func newJTI() (string, error) {
	b := make([]byte, 32)
	if _, err := rand.Read(b); err != nil {
		return "", err
	}
	return base64.RawURLEncoding.EncodeToString(b), nil
}
`, mod, mod)
}

func authTokenStoreGo() string {
	return `package auth

import (
	"database/sql"
	"errors"
	"time"
)

var ErrTokenRevoked = errors.New("token is revoked")

type TokenStore struct {
	db *sql.DB
}

type TokenRecord struct {
	JTI string
	UserID int64
	Email string
	TokenType string
	ExpiresAt time.Time
}

func NewTokenStore(db *sql.DB) *TokenStore {
	return &TokenStore{db: db}
}

func (s *TokenStore) Store(claims *Claims, tokenHash string, ipAddress, userAgent string) error {
	_, err := s.db.Exec(
		` + "`" + `INSERT INTO user_tokens (user_id, jti, token_hash, token_type, ip_address, user_agent, expires_at, created_at)
		 VALUES ($1, $2, $3, $4, $5, $6, $7, $8)` + "`" + `,
		claims.UserID, claims.ID, tokenHash, claims.TokenType, ipAddress, userAgent, claims.ExpiresAt.Time, time.Now(),
	)
	return err
}

func (s *TokenStore) EnsureActive(jti, tokenType string) error {
	var revokedAt sql.NullTime
	var expiresAt time.Time
	err := s.db.QueryRow(
		` + "`" + `SELECT ut.revoked_at, ut.expires_at
		 FROM user_tokens ut
		 JOIN users u ON u.id = ut.user_id
		 WHERE ut.jti = $1 AND ut.token_type = $2 AND u.is_active = true
		 LIMIT 1` + "`" + `,
		jti, tokenType,
	).Scan(&revokedAt, &expiresAt)
	if err != nil {
		return err
	}
	if revokedAt.Valid || time.Now().After(expiresAt) {
		return ErrTokenRevoked
	}
	return nil
}

func (s *TokenStore) FindActiveRefreshByHash(tokenHash string) (*TokenRecord, error) {
	var rec TokenRecord
	var revokedAt sql.NullTime
	err := s.db.QueryRow(
		` + "`" + `SELECT ut.user_id, u.email, ut.jti, ut.token_type, ut.expires_at, ut.revoked_at
		 FROM user_tokens ut
		 JOIN users u ON u.id = ut.user_id
		 WHERE ut.token_hash = $1 AND ut.token_type = $2 AND u.is_active = true
		 LIMIT 1` + "`" + `,
		tokenHash, TokenTypeRefresh,
	).Scan(&rec.UserID, &rec.Email, &rec.JTI, &rec.TokenType, &rec.ExpiresAt, &revokedAt)
	if err != nil {
		return nil, err
	}
	if revokedAt.Valid || time.Now().After(rec.ExpiresAt) {
		return nil, ErrTokenRevoked
	}
	return &rec, nil
}

func (s *TokenStore) RevokeJTI(jti string) error {
	_, err := s.db.Exec(` + "`" + `UPDATE user_tokens SET revoked_at = COALESCE(revoked_at, $1) WHERE jti = $2` + "`" + `, time.Now(), jti)
	return err
}

func (s *TokenStore) RotateRefresh(oldJTI, newJTI string) error {
	_, err := s.db.Exec(
		` + "`" + `UPDATE user_tokens SET revoked_at = COALESCE(revoked_at, $1), replaced_by_jti = $2
		 WHERE jti = $3 AND token_type = $4` + "`" + `,
		time.Now(), newJTI, oldJTI, TokenTypeRefresh,
	)
	return err
}
`
}

func authMiddlewareGo(mod string) string {
	return fmt.Sprintf(`package middleware

import (
	"context"
	"database/sql"
	"encoding/json"
	"net/http"
	"strings"

	"%s/internal/auth"
	"%s/internal/config"
)

type contextKey string

const (
	UserIDKey contextKey = "user_id"
	UserEmailKey contextKey = "user_email"
	TokenJTIKey contextKey = "token_jti"
)

func Auth(cfg *config.Config, db *sql.DB, next http.Handler) http.Handler {
	tokenStore := auth.NewTokenStore(db)
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		parts := strings.SplitN(r.Header.Get("Authorization"), " ", 2)
		if len(parts) != 2 || strings.ToLower(parts[0]) != "bearer" {
			writeError(w, http.StatusUnauthorized, "authorization required")
			return
		}

		claims, err := auth.ParseToken(parts[1], cfg)
		if err != nil || claims.TokenType != auth.TokenTypeAccess {
			writeError(w, http.StatusUnauthorized, "invalid token")
			return
		}
		if err := tokenStore.EnsureActive(claims.ID, auth.TokenTypeAccess); err != nil {
			writeError(w, http.StatusUnauthorized, "token revoked or expired")
			return
		}

		ctx := r.Context()
		ctx = context.WithValue(ctx, UserIDKey, claims.UserID)
		ctx = context.WithValue(ctx, UserEmailKey, claims.Email)
		ctx = context.WithValue(ctx, TokenJTIKey, claims.ID)
		next.ServeHTTP(w, r.WithContext(ctx))
	})
}

func UserID(r *http.Request) (int64, bool) {
	id, ok := r.Context().Value(UserIDKey).(int64)
	return id, ok
}

func UserEmail(r *http.Request) (string, bool) {
	email, ok := r.Context().Value(UserEmailKey).(string)
	return email, ok
}

func TokenJTI(r *http.Request) (string, bool) {
	jti, ok := r.Context().Value(TokenJTIKey).(string)
	return jti, ok
}

func writeError(w http.ResponseWriter, status int, message string) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	_ = json.NewEncoder(w).Encode(map[string]string{"error": message})
}
`, mod, mod)
}

func authUserModelGo() string {
	return `package models

import "time"

type User struct {
	ID int64 ` + "`json:\"id\"`" + `
	Name string ` + "`json:\"name\"`" + `
	Email string ` + "`json:\"email\"`" + `
	PasswordHash string ` + "`json:\"-\"`" + `
	IsActive bool ` + "`json:\"is_active\"`" + `
	CreatedAt time.Time ` + "`json:\"created_at\"`" + `
	UpdatedAt time.Time ` + "`json:\"updated_at\"`" + `
}

type UserResponse struct {
	ID int64 ` + "`json:\"id\"`" + `
	Name string ` + "`json:\"name\"`" + `
	Email string ` + "`json:\"email\"`" + `
	IsActive bool ` + "`json:\"is_active\"`" + `
}

type RegisterRequest struct {
	Name string ` + "`json:\"name\"`" + `
	Email string ` + "`json:\"email\"`" + `
	Password string ` + "`json:\"password\"`" + `
}

type LoginRequest struct {
	Email string ` + "`json:\"email\"`" + `
	Password string ` + "`json:\"password\"`" + `
}

type RefreshRequest struct {
	RefreshToken string ` + "`json:\"refresh_token\"`" + `
}

type LogoutRequest struct {
	RefreshToken string ` + "`json:\"refresh_token\"`" + `
}

func (u *User) Response() UserResponse {
	return UserResponse{ID: u.ID, Name: u.Name, Email: u.Email, IsActive: u.IsActive}
}
`
}

func authUserRepositoryGo(mod string) string {
	return fmt.Sprintf(`package repositories

import (
	"database/sql"
	"errors"

	"%s/internal/models"
)

type UserRepository struct {
	db *sql.DB
}

func NewUserRepository(db *sql.DB) *UserRepository {
	return &UserRepository{db: db}
}

func (r *UserRepository) Create(u *models.User) error {
	return r.db.QueryRow(
		`+"`"+`INSERT INTO users (name, email, password_hash, is_active, created_at, updated_at)
		 VALUES ($1, $2, $3, true, NOW(), NOW())
		 RETURNING id, is_active, created_at, updated_at`+"`"+`,
		u.Name, u.Email, u.PasswordHash,
	).Scan(&u.ID, &u.IsActive, &u.CreatedAt, &u.UpdatedAt)
}

func (r *UserRepository) FindByEmail(email string) (*models.User, error) {
	return r.find(`+"`"+`SELECT id, name, email, password_hash, is_active, created_at, updated_at FROM users WHERE email = $1 LIMIT 1`+"`"+`, email)
}

func (r *UserRepository) FindByID(id int64) (*models.User, error) {
	return r.find(`+"`"+`SELECT id, name, email, password_hash, is_active, created_at, updated_at FROM users WHERE id = $1 LIMIT 1`+"`"+`, id)
}

func (r *UserRepository) find(query string, arg any) (*models.User, error) {
	var u models.User
	err := r.db.QueryRow(query, arg).Scan(&u.ID, &u.Name, &u.Email, &u.PasswordHash, &u.IsActive, &u.CreatedAt, &u.UpdatedAt)
	if errors.Is(err, sql.ErrNoRows) {
		return nil, err
	}
	if err != nil {
		return nil, err
	}
	return &u, nil
}
`, mod)
}

func authUserServiceGo(mod string) string {
	return fmt.Sprintf(`package services

import (
	"database/sql"
	"errors"
	"fmt"
	"strings"

	"golang.org/x/crypto/bcrypt"

	"%s/internal/models"
	"%s/internal/repositories"
)

type UserService struct {
	repo *repositories.UserRepository
}

func NewUserService(repo *repositories.UserRepository) *UserService {
	return &UserService{repo: repo}
}

func (s *UserService) Register(req models.RegisterRequest) (*models.User, error) {
	req.Email = strings.TrimSpace(strings.ToLower(req.Email))
	req.Name = strings.TrimSpace(req.Name)
	if req.Name == "" || req.Email == "" || len(req.Password) < 8 {
		return nil, fmt.Errorf("name, valid email, and password with at least 8 characters are required")
	}

	hash, err := bcrypt.GenerateFromPassword([]byte(req.Password), bcrypt.DefaultCost)
	if err != nil {
		return nil, err
	}

	u := &models.User{Name: req.Name, Email: req.Email, PasswordHash: string(hash)}
	if err := s.repo.Create(u); err != nil {
		return nil, err
	}
	return u, nil
}

func (s *UserService) Authenticate(email, password string) (*models.User, error) {
	u, err := s.repo.FindByEmail(strings.TrimSpace(strings.ToLower(email)))
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, fmt.Errorf("invalid credentials")
		}
		return nil, err
	}
	if !u.IsActive {
		return nil, fmt.Errorf("user is inactive")
	}
	if err := bcrypt.CompareHashAndPassword([]byte(u.PasswordHash), []byte(password)); err != nil {
		return nil, fmt.Errorf("invalid credentials")
	}
	return u, nil
}

func (s *UserService) FindByID(id int64) (*models.User, error) {
	return s.repo.FindByID(id)
}
`, mod, mod)
}

func authHandlerGo(mod string) string {
	return fmt.Sprintf(`package handlers

import (
	"database/sql"
	"encoding/json"
	"net/http"

	"%s/internal/auth"
	"%s/internal/config"
	"%s/internal/middleware"
	"%s/internal/models"
	"%s/internal/repositories"
	"%s/internal/services"
)

type AuthHandler struct {
	users *services.UserService
	cfg *config.Config
	tokenStore *auth.TokenStore
}

func NewAuthHandler(db *sql.DB, cfg *config.Config) *AuthHandler {
	repo := repositories.NewUserRepository(db)
	return &AuthHandler{users: services.NewUserService(repo), cfg: cfg, tokenStore: auth.NewTokenStore(db)}
}

func (h *AuthHandler) Register(w http.ResponseWriter, r *http.Request) {
	var req models.RegisterRequest
	if !decodeJSON(w, r, &req) {
		return
	}
	user, err := h.users.Register(req)
	if err != nil {
		writeError(w, http.StatusBadRequest, err.Error())
		return
	}
	writeJSON(w, http.StatusCreated, map[string]any{"user": user.Response()})
}

func (h *AuthHandler) Login(w http.ResponseWriter, r *http.Request) {
	var req models.LoginRequest
	if !decodeJSON(w, r, &req) {
		return
	}
	user, err := h.users.Authenticate(req.Email, req.Password)
	if err != nil {
		writeError(w, http.StatusUnauthorized, "invalid credentials")
		return
	}
	tokens, accessClaims, refreshClaims, err := auth.GenerateTokenPair(user, h.cfg)
	if err != nil {
		writeError(w, http.StatusInternalServerError, "failed to generate token")
		return
	}
	if err := h.storeTokenPair(r, tokens, accessClaims, refreshClaims); err != nil {
		writeError(w, http.StatusInternalServerError, "failed to store token")
		return
	}
	writeJSON(w, http.StatusOK, tokens)
}

func (h *AuthHandler) Refresh(w http.ResponseWriter, r *http.Request) {
	var req models.RefreshRequest
	if !decodeJSON(w, r, &req) {
		return
	}
	claims, err := auth.ParseToken(req.RefreshToken, h.cfg)
	if err != nil || claims.TokenType != auth.TokenTypeRefresh {
		writeError(w, http.StatusUnauthorized, "invalid refresh token")
		return
	}

	record, err := h.tokenStore.FindActiveRefreshByHash(auth.HashToken(req.RefreshToken))
	if err != nil || record.JTI != claims.ID || record.UserID != claims.UserID {
		writeError(w, http.StatusUnauthorized, "refresh token revoked or expired")
		return
	}

	user := &models.User{ID: claims.UserID, Email: record.Email, IsActive: true}
	tokens, accessClaims, refreshClaims, err := auth.GenerateTokenPair(user, h.cfg)
	if err != nil {
		writeError(w, http.StatusInternalServerError, "failed to generate token")
		return
	}
	if err := h.storeTokenPair(r, tokens, accessClaims, refreshClaims); err != nil {
		writeError(w, http.StatusInternalServerError, "failed to store token")
		return
	}
	if err := h.tokenStore.RotateRefresh(claims.ID, refreshClaims.ID); err != nil {
		writeError(w, http.StatusInternalServerError, "failed to rotate refresh token")
		return
	}
	writeJSON(w, http.StatusOK, tokens)
}

func (h *AuthHandler) Logout(w http.ResponseWriter, r *http.Request) {
	if jti, ok := middleware.TokenJTI(r); ok {
		_ = h.tokenStore.RevokeJTI(jti)
	}
	var req models.LogoutRequest
	if json.NewDecoder(r.Body).Decode(&req) == nil && req.RefreshToken != "" {
		if claims, err := auth.ParseToken(req.RefreshToken, h.cfg); err == nil && claims.TokenType == auth.TokenTypeRefresh {
			_ = h.tokenStore.RevokeJTI(claims.ID)
		}
	}
	writeJSON(w, http.StatusOK, map[string]string{"message": "logout successful"})
}

func (h *AuthHandler) Me(w http.ResponseWriter, r *http.Request) {
	id, ok := middleware.UserID(r)
	if !ok {
		writeError(w, http.StatusUnauthorized, "authorization required")
		return
	}
	user, err := h.users.FindByID(id)
	if err != nil {
		writeError(w, http.StatusNotFound, "user not found")
		return
	}
	writeJSON(w, http.StatusOK, user.Response())
}

func (h *AuthHandler) storeTokenPair(r *http.Request, tokens *auth.TokenPair, accessClaims, refreshClaims *auth.Claims) error {
	ipAddress := r.RemoteAddr
	userAgent := r.UserAgent()
	if err := h.tokenStore.Store(accessClaims, auth.HashToken(tokens.AccessToken), ipAddress, userAgent); err != nil {
		return err
	}
	return h.tokenStore.Store(refreshClaims, auth.HashToken(tokens.RefreshToken), ipAddress, userAgent)
}

func decodeJSON(w http.ResponseWriter, r *http.Request, dest any) bool {
	defer r.Body.Close()
	if err := json.NewDecoder(r.Body).Decode(dest); err != nil {
		writeError(w, http.StatusBadRequest, "invalid request body")
		return false
	}
	return true
}

func writeJSON(w http.ResponseWriter, status int, v any) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	_ = json.NewEncoder(w).Encode(v)
}

func writeError(w http.ResponseWriter, status int, message string) {
	writeJSON(w, status, map[string]string{"error": message})
}
`, mod, mod, mod, mod, mod, mod)
}

func authRoutesGo(mod string) string {
	return fmt.Sprintf(`package routes

import (
	"database/sql"
	"net/http"

	"%s/internal/config"
	"%s/internal/handlers"
	"%s/internal/middleware"
)

func Register(mux *http.ServeMux, db *sql.DB, cfg *config.Config) {
	authHandler := handlers.NewAuthHandler(db, cfg)

	mux.HandleFunc("POST /auth/register", authHandler.Register)
	mux.HandleFunc("POST /auth/login", authHandler.Login)
	mux.HandleFunc("POST /auth/refresh", authHandler.Refresh)
	mux.Handle("POST /auth/logout", middleware.Auth(cfg, db, http.HandlerFunc(authHandler.Logout)))
	mux.Handle("GET /me", middleware.Auth(cfg, db, http.HandlerFunc(authHandler.Me)))
}
`, mod, mod, mod)
}

func authUsersMigrationUp() string {
	return `CREATE TABLE IF NOT EXISTS users (
  id BIGSERIAL PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS user_tokens (
  id BIGSERIAL PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  jti VARCHAR(96) NOT NULL UNIQUE,
  token_hash CHAR(64) NOT NULL UNIQUE,
  token_type VARCHAR(20) NOT NULL,
  ip_address VARCHAR(64),
  user_agent VARCHAR(255),
  expires_at TIMESTAMPTZ NOT NULL,
  revoked_at TIMESTAMPTZ,
  replaced_by_jti VARCHAR(96),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_user_tokens_user_id ON user_tokens(user_id);
CREATE INDEX IF NOT EXISTS idx_user_tokens_token_type ON user_tokens(token_type);
CREATE INDEX IF NOT EXISTS idx_user_tokens_expires_at ON user_tokens(expires_at);
`
}
